# Reload config bind
bind r source ~/.tmux.conf\; display "~/.tmux.conf sourced!"

# Handle vim mode switching delay
set -s escape-time 5

set -g base-index 1

# Vim binding keys
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Enable mouse mode
set -g mouse on

# Disable windows automatically rename
set-option -g allow-rename off

# Enable vim mode
setw -g mode-keys vi

# Make the focused pane stand out clearly
set -g pane-active-border-style 'fg=cyan'
set -g pane-border-status top
set -g pane-border-format ''

# Status bar
set -g status-left ""
set -g status-style bg=default
set-window-option -g window-status-style fg=white,bg=default
set-window-option -g window-status-current-style fg=black,bg=cyan,bold
set -g status-right "#[fg=cyan] %I:%M %d-%m-%Y "
set -g status-right-length 50